version: '3'
services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"

  ml_client:
    build: ./ml_client
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=emotion_db
      - MONGODB_COLLECTION=emotion_records
    depends_on:
      - mongodb

  web-app:
    build: ./web-app
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=emotion_db
      - MONGODB_COLLECTION=emotion_records
    depends_on:
      - mongodb