version: '3'
services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"

  ml_client:
    build: ./machine-learning-client
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://27017:27017
      - MONGO_DBNAME=emotion_db
      - MONGODB_COLLECTION=emotion_records
    depends_on:
      - mongodb

  web-app:
    build: ./web-app
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://27017:27017
      - MONGO_DBNAME=emotion_db
      - MONGODB_COLLECTION=emotion_records
    depends_on:
      - mongodb